# Generated by Django 4.0.5 on 2022-06-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIacronexApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinas',
            name='estado',
            field=models.CharField(default='alta', max_length=4),
            preserve_default=False,
        ),
    ]
